# Default configuration for radar-only trajectory reconstruction

paths:
  radar_csv: "S1_Hatala_83_sufa_trimmed (1).csv"
  telemetry_csv: "Telemetric Output Conversion.csv"
  out_dir: "outputs/run_$(date +%Y%m%d_%H%M%S)"

mapping:
  # Robust column mapping: project-specific names to canonical {time, lat, lon, alt, vx, vy, vz, doppler, slant_range}
  radar:
    time: ["time", "t", "timestamp", "Time"]
    lat: ["lat", "latitude", "lat_s", "Weapon LAT (deg)", "Latitude"]
    lon: ["lon", "longitude", "lon_s", "Weapon LON (deg)", "Longitude"]
    alt: ["alt", "altitude", "h", "alt_s", "Weapon ALT (ft)", "Altitude"]
    doppler: ["doppler", "range_rate", "vr"]
    slant_range: ["slant_range", "range", "R"]
  telemetry:
    time: ["time", "t", "timestamp", "Time"]
    lat: ["lat", "latitude", "Weapon LAT (deg)", "Lat", "Latitude"]
    lon: ["lon", "longitude", "Weapon LON (deg)", "Lon", "Longitude"]
    alt: ["alt", "altitude", "h", "Weapon ALT (ft)", "Altitude"]
    vx: ["vx", "vel_x", "Velocity X", "Vx"]
    vy: ["vy", "vel_y", "Velocity Y", "Vy"]
    vz: ["vz", "vel_z", "Velocity Z", "Vz"]

preprocessing:
  dt: 0.1
  outlier_iqr_factor: 1.5
  savgol_window: 9
  savgol_polyorder: 3

alignment:
  max_lag_seconds: 0.2
  expect_lag_lt: 0.05

weights:
  auto_calibrate: true
  eta: 10.0
  gamma: 0.1

solver:
  enable_scaling: true
  alpha_p: null
  alpha_v: null
  enable_soc: true
  theta_max_deg: 20
  terminal_altitude_window_m: [ -500.0, 500.0 ]
  terminal_xy_box_m: 8000.0
  osqp:
    eps_abs: 2.0e-5
    eps_rel: 2.0e-5
    max_iter: 200000
  ecos:
    abstol: 5.0e-7
    reltol: 5.0e-7

outer:
  k_min: 0.02
  k_max: 0.5
  k_grid_points: 21
  tol_k: 1.0e-3
  tol_J: 1.0e-3
  max_iters: 30

ablations:
  theta_grid_deg: [10, 15, 20, 25, 30]
  grid_points: [9, 21]
  enable_soc_ablation: false
  enable_theta_sensitivity: false

reproducibility:
  seed: 42

sanity_checks:
  position_scale:
    enforce: "warn"   # "warn" or "error"
    abs_position_median_max_m: 20000.0
    median_step_max_m: 2000.0
    hard_max_m: 10000000.0
